name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install 
      
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

  deploy:
    steps:
      - uses: actions/checkout@v2
      - uses: JamesIves/github-pages-deploy-action@v4.2.3
          with:
            branch: gh-pages
            folder: build
