name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install 
      
      - name: Build project
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Deploy project
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: build
